import { initTheme } from '@/utils/theme';

import Header from '@/components/Headers/Header';
import Footer from '@/components/Footers/Footer';
import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function() {
              ${initTheme.toString()}
              initTheme();
            })()`,
          }}
        />
        <Header />
        <main className="flex flex-col w-full mx-auto max-w-screen-2xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
