import Header from '@/components/Headers/Header';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex flex-col w-full max-w-screen-2xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
